// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataBodySlice =
  | TextSlice
  | AwardItemsSlice
  | TalkItemsSlice
  | JobItemsSlice;

/**
 * Content for About Page documents
 */
interface AboutDocumentData {
  /**
   * Profile Photo field in *About Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.profile_photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_photo: prismic.ImageField<never>;

  /**
   * description field in *About Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * About field in *About Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.about
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about: prismic.RichTextField;

  /**
   * Slice Zone field in *About Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<AboutDocumentDataBodySlice>;
}

/**
 * About Page document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

type AboutNewDocumentDataSlicesSlice =
  | TextSlice
  | AwardItemsSlice
  | JobItemsSlice
  | TalkItemsSlice;

/**
 * Content for About New documents
 */
interface AboutNewDocumentData {
  /**
   * Profile Photo field in *About New*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_new.profile_photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_photo: prismic.ImageField<never>;

  /**
   * Description field in *About New*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_new.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * About field in *About New*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_new.about
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about: prismic.RichTextField;

  /**
   * Slice Zone field in *About New*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_new.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutNewDocumentDataSlicesSlice> /**
   * Meta Title field in *About New*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_new.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About New*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_new.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About New*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_new.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About New document from Prismic
 *
 * - **API ID**: `about_new`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutNewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AboutNewDocumentData>,
    "about_new",
    Lang
  >;

/**
 * Content for Award documents
 */
interface AwardDocumentData {
  /**
   * Title field in *Award*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: award.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *Award*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: award.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.TitleField;

  /**
   * Description field in *Award*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: award.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Date field in *Award*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: award.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;
}

/**
 * Award document from Prismic
 *
 * - **API ID**: `award`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AwardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AwardDocumentData>, "award", Lang>;

type BlogHomeDocumentDataSlicesSlice = never;

/**
 * Content for Blog Home documents
 */
interface BlogHomeDocumentData {
  /**
   * Headline field in *Blog Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Main title...
   * - **API ID Path**: blog_home.headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * Description field in *Blog Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sub-title...
   * - **API ID Path**: blog_home.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Blog Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * `slices` field in *Blog Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogHomeDocumentDataSlicesSlice>;
}

/**
 * Blog Home document from Prismic
 *
 * - **API ID**: `blog_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogHomeDocumentData>,
    "blog_home",
    Lang
  >;

type BlogPostDocumentDataSlicesSlice = HtmlCodeSlice | TextSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Date field in *Blog Post*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date: prismic.TimestampField;

  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * thumbnail field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Item in *Header → Navigation*
 */
export interface HeaderDocumentDataNavigationItem {
  /**
   * Link field in *Header → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *Header → Navigation*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].link_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  link_text: prismic.TitleField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Site Name field in *Header*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: header.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  site_name: prismic.TitleField;

  /**
   * Site Description field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.site_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  site_description: prismic.RichTextField;

  /**
   * Navigation field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<HeaderDocumentDataNavigationItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

/**
 * Item in *Home → Work*
 */
export interface HomeDocumentDataWorkItem {
  /**
   * Work Item field in *Home → Work*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.work[].work_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  work_item: prismic.ContentRelationshipField<"work">;
}

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Work field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.work[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  work: prismic.GroupField<Simplify<HomeDocumentDataWorkItem>>;

  /**
   * `slices` field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Job → Roles*
 */
export interface JobDocumentDataRolesItem {
  /**
   * Role field in *Job → Roles*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: job.roles[].role
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.TitleField;

  /**
   * Start Date field in *Job → Roles*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job.roles[].date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * End Date field in *Job → Roles*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job.roles[].end_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * Present Job field in *Job → Roles*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: job.roles[].present_job
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  present_job: prismic.BooleanField;

  /**
   * description field in *Job → Roles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.roles[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *Job → Related Work*
 */
export interface JobDocumentDataRelatedWorkItem {
  /**
   * Work field in *Job → Related Work*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: job.related_work[].work
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  work: prismic.ContentRelationshipField<"work">;
}

/**
 * Item in *Job → Recommendations*
 */
export interface JobDocumentDataRecommendationsItem {
  /**
   * Recommendation Body field in *Job → Recommendations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.recommendations[].recommendation_body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  recommendation_body: prismic.RichTextField;
}

/**
 * Content for Job documents
 */
interface JobDocumentData {
  /**
   * Title field in *Job*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: job.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Roles field in *Job*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job.roles[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  roles: prismic.GroupField<Simplify<JobDocumentDataRolesItem>>;

  /**
   * Related Work field in *Job*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job.related_work[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  related_work: prismic.GroupField<Simplify<JobDocumentDataRelatedWorkItem>>;

  /**
   * Recommendations field in *Job*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job.recommendations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  recommendations: prismic.GroupField<
    Simplify<JobDocumentDataRecommendationsItem>
  >;
}

/**
 * Job document from Prismic
 *
 * - **API ID**: `job`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<JobDocumentData>, "job", Lang>;

/**
 * Primary content in *Post → Slice zone → Quote → Primary*
 */
export interface PostDocumentDataBodyQuoteSlicePrimary {
  /**
   * Quote field in *Post → Slice zone → Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Post Quote...
   * - **API ID Path**: post.body[].quote.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;
}

/**
 * Slice for *Post → Slice zone*
 */
export type PostDocumentDataBodyQuoteSlice = prismic.Slice<
  "quote",
  Simplify<PostDocumentDataBodyQuoteSlicePrimary>,
  never
>;

/**
 * Primary content in *Post → Slice zone → Image with Caption → Primary*
 */
export interface PostDocumentDataBodyImageWithCaptionSlicePrimary {
  /**
   * Image field in *Post → Slice zone → Image with Caption → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.body[].image_with_caption.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Post → Slice zone → Image with Caption → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Image Caption...
   * - **API ID Path**: post.body[].image_with_caption.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.TitleField;
}

/**
 * Slice for *Post → Slice zone*
 */
export type PostDocumentDataBodyImageWithCaptionSlice = prismic.Slice<
  "image_with_caption",
  Simplify<PostDocumentDataBodyImageWithCaptionSlicePrimary>,
  never
>;

type PostDocumentDataBodySlice =
  | PostDocumentDataBodyQuoteSlice
  | PostDocumentDataBodyImageWithCaptionSlice;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Title field in *Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Blog Post Title...
   * - **API ID Path**: post.title
   * - **Tab**: Blog Post
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Date field in *Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: post.date
   * - **Tab**: Blog Post
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * thumbnail field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.thumbnail
   * - **Tab**: Blog Post
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Slice zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.body[]
   * - **Tab**: Blog Post
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<PostDocumentDataBodySlice>;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Content for Talk documents
 */
interface TalkDocumentData {
  /**
   * Title field in *Talk*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Talk*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Date field in *Talk*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: talk.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;
}

/**
 * Talk document from Prismic
 *
 * - **API ID**: `talk`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TalkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TalkDocumentData>, "talk", Lang>;

/**
 * Item in *Work → media*
 */
export interface WorkDocumentDataMediaItem {
  /**
   * image field in *Work → media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.media[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * YouTube ID field in *Work → media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.media[].youtube_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtube_id: prismic.KeyTextField;

  /**
   * Is Playlist field in *Work → media*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: work.media[].is_playlist
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_playlist: prismic.BooleanField;
}

type WorkDocumentDataSlicesSlice = never;

/**
 * Content for Work documents
 */
interface WorkDocumentData {
  /**
   * Title field in *Work*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: work.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *Work*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * thumbnail field in *Work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<"relatedWork">;

  /**
   * body field in *Work*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * media field in *Work*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  media: prismic.GroupField<Simplify<WorkDocumentDataMediaItem>>;

  /**
   * Slice Zone field in *Work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WorkDocumentDataSlicesSlice>;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | AboutNewDocument
  | AwardDocument
  | BlogHomeDocument
  | BlogPostDocument
  | HeaderDocument
  | HomeDocument
  | JobDocument
  | PostDocument
  | TalkDocument
  | WorkDocument;

/**
 * Primary content in *AwardItems → Items*
 */
export interface AwardItemsSliceDefaultItem {
  /**
   * Award field in *AwardItems → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: AwardItems.items[].award
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  award: prismic.ContentRelationshipField<"award">;
}

/**
 * Default variation for AwardItems Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardItemsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<AwardItemsSliceDefaultItem>
>;

/**
 * Slice variation for *AwardItems*
 */
type AwardItemsSliceVariation = AwardItemsSliceDefault;

/**
 * AwardItems Shared Slice
 *
 * - **API ID**: `AwardItems`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardItemsSlice = prismic.SharedSlice<
  "AwardItems",
  AwardItemsSliceVariation
>;

/**
 * Primary content in *JobItems → Items*
 */
export interface JobItemsSliceDefaultItem {
  /**
   * Job field in *JobItems → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: JobItems.items[].job
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  job: prismic.ContentRelationshipField<"job">;
}

/**
 * Default variation for JobItems Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobItemsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<JobItemsSliceDefaultItem>
>;

/**
 * Slice variation for *JobItems*
 */
type JobItemsSliceVariation = JobItemsSliceDefault;

/**
 * JobItems Shared Slice
 *
 * - **API ID**: `JobItems`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobItemsSlice = prismic.SharedSlice<
  "JobItems",
  JobItemsSliceVariation
>;

/**
 * Primary content in *TalkItems → Items*
 */
export interface TalkItemsSliceDefaultItem {
  /**
   * Talk field in *TalkItems → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: TalkItems.items[].talk
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  talk: prismic.ContentRelationshipField<"talk">;
}

/**
 * Default variation for TalkItems Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TalkItemsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TalkItemsSliceDefaultItem>
>;

/**
 * Slice variation for *TalkItems*
 */
type TalkItemsSliceVariation = TalkItemsSliceDefault;

/**
 * TalkItems Shared Slice
 *
 * - **API ID**: `TalkItems`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TalkItemsSlice = prismic.SharedSlice<
  "TalkItems",
  TalkItemsSliceVariation
>;

/**
 * Primary content in *HtmlCode → Default → Primary*
 */
export interface HtmlCodeSliceDefaultPrimary {
  /**
   * HTML field in *HtmlCode → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: html_code.default.primary.html
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  html: prismic.KeyTextField;
}

/**
 * Default variation for HtmlCode Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HtmlCodeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HtmlCodeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HtmlCode*
 */
type HtmlCodeSliceVariation = HtmlCodeSliceDefault;

/**
 * HtmlCode Shared Slice
 *
 * - **API ID**: `html_code`
 * - **Description**: HtmlCode
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HtmlCodeSlice = prismic.SharedSlice<
  "html_code",
  HtmlCodeSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Rich Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.richText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richText: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → Horizontal List → Primary*
 */
export interface TextSliceHorizontalListPrimary {
  /**
   * Rich Text field in *Text → Horizontal List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.horizontalList.primary.richText
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richText: prismic.RichTextField;
}

/**
 * Horizontal List variation for Text Slice
 *
 * - **API ID**: `horizontalList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceHorizontalList = prismic.SharedSliceVariation<
  "horizontalList",
  Simplify<TextSliceHorizontalListPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault | TextSliceHorizontalList;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataBodySlice,
      AboutNewDocument,
      AboutNewDocumentData,
      AboutNewDocumentDataSlicesSlice,
      AwardDocument,
      AwardDocumentData,
      BlogHomeDocument,
      BlogHomeDocumentData,
      BlogHomeDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataWorkItem,
      HomeDocumentDataSlicesSlice,
      JobDocument,
      JobDocumentData,
      JobDocumentDataRolesItem,
      JobDocumentDataRelatedWorkItem,
      JobDocumentDataRecommendationsItem,
      PostDocument,
      PostDocumentData,
      PostDocumentDataBodyQuoteSlicePrimary,
      PostDocumentDataBodyImageWithCaptionSlicePrimary,
      PostDocumentDataBodySlice,
      TalkDocument,
      TalkDocumentData,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataMediaItem,
      WorkDocumentDataSlicesSlice,
      AllDocumentTypes,
      AwardItemsSlice,
      AwardItemsSliceDefaultItem,
      AwardItemsSliceVariation,
      AwardItemsSliceDefault,
      JobItemsSlice,
      JobItemsSliceDefaultItem,
      JobItemsSliceVariation,
      JobItemsSliceDefault,
      TalkItemsSlice,
      TalkItemsSliceDefaultItem,
      TalkItemsSliceVariation,
      TalkItemsSliceDefault,
      HtmlCodeSlice,
      HtmlCodeSliceDefaultPrimary,
      HtmlCodeSliceVariation,
      HtmlCodeSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceHorizontalListPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceHorizontalList,
    };
  }
}
