// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  AwardItems: defineAsyncComponent(() => import("./AwardItems/index.vue")),
  JobItems: defineAsyncComponent(() => import("./JobItems/index.vue")),
  TalkItems: defineAsyncComponent(() => import("./TalkItems/index.vue")),
  html_code: defineAsyncComponent(() => import("./HtmlCode/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
});
